### ISSUE TITLE
User Story 7: Completion Modal

### ISSUE THREAD

**Issue by Asad-1I** [CharlesTack/JavaScriptQuiz#10]
**User Story 7: Completion Modal**
As a regular user of quiz sites, I like to feel the satisfaction knowing the score I got after completing a quiz so that I can increase my self-esteem and improve on any gaps in knowledge.

**Acceptance Criteria:**
- [x] The site should let the user know final score on completion of the quiz.
- [x] Modal should have a reset button so the user can start the quiz again and improve their previous score

**Tasks:**
- [x] Code a modal window which appears on submission of the last answer.
- [x] Integrate final score and quiz complete message into modal.
