### ISSUE TITLE
User Story 13: Instructions Modal

### ISSUE THREAD

**Issue by Asad-1I** [CharlesTack/JavaScriptQuiz#12]
User Story 13: Instructions Modal

*User Story 13: Instructions:*
As a new user to the site I would like instructions to be presented to me so that I can easily user the site without barriers.

**Acceptance Criteria:**
- [x] A modal window should be available (either by clicking an instructions button or automatically).
- [x] The modal window should contain instructions on how to complete the quiz and key functionality

**Tasks:**
- [x] Code a modal message window
- [x] Implement instruction text
