### ISSUE TITLE
User Story 9: Responsive Messages

### ISSUE THREAD

**Issue by Asad-1I** [CharlesTack/JavaScriptQuiz#15]
User Story 9: Responsive Messages

**User Story: Responsive Messages:**
As a frequent quiz user I like messages to be tailored to my attainment level so that I can feel an appropriate level of satisfaction with my performance.

**Acceptance Criteria:**
- [ ] The congratulations message should be customised depending on the amount of correct answers.
- [ ] For 1-3 correct it should say "Thanks for participating, keep studying and try again!"
- [ ] For 4-6 correct answers is should say "Thanks for participating, your knowledge is really getting there!"
- [ ] For 7-10 correct answers is should say "Thanks for participating, Google should call you!"

**Tasks:**
- [ ] Recode the modal message to provide different responses depending on score.
