### ISSUE TITLE
User Story 10: Game expansions

### ISSUE THREAD

**Issue by Asad-1I** [CharlesTack/JavaScriptQuiz#16]
**User Story 10: Game expansions:**
As a avid quiz fan and user of the site, I would like extra game types for different coding languages and the ability to customise how many questions I'm presented with, so that I can keep things fresh and continue my learning.

**Acceptance Criteria:**
- [ ] The application should have options to change to different coding languages
- [ ] The user should be able to extend the number of questions they're asked.
- [ ] Intergrate AI to keep asking new questions.

**Tasks:**
- [ ] Add alternative versions of the quiz for HTML, CSS, Python, etc.
- [ ] Increase the question bank and provide controls to select number of questions.
- [ ] Code to include AI for asking questions on the fly (endless mode!)
