### ISSUE TITLE
User Story 6: Familiarity and usability

### ISSUE THREAD

**Issue by Asad-1I** [CharlesTack/JavaScriptQuiz#2]
**User Story 6: Appearance and usability**:
As a regular quiz user I want to be presented with a single screen quiz which is familiar, intuitive and logical in layout to me so that I can easily operate the quiz and navigate the site.

**Acceptance Criteria:**
- [x] The layout should be logical, familiar and intuitive
- [x] The quiz function should be similar to other quiz sites
- [x] A reset/retry button is present to allow the user to try again
- [x] The user can track how many questions they have answered and how many they have left to answer
- [x] The site should have an attractive hero image/background which is suitable for the subject matter.

**Tasks:**
- [x] Use HTML, CSS and Bootstrap to create a page which is laid out in a logical manner
- [x] Research other quiz sites and utilise similar layouts
- [x] Code a reset/retry button
- [ ] Code a question counter section
- [x] Locate/create image in WebP format for background/hero.
