### ISSUE TITLE
User Story 16: Improve Visibility

### ISSUE THREAD

**Issue by CharlesTack** [CharlesTack/JavaScriptQuiz#23]
**User Story 16: Improve Visibility:"
As a user with visual difficulty, I would like the option to change the colour scheme and appearance of the site to make it easier to read for a better and more accessible user experience.

**Acceptance criteria:**
- [ ] A button is added to change the colour scheme
- [ ] A button is added to change the opacity of main areas to solid colours

**Tasks:**
- [ ] Code up buttons
