### ISSUE TITLE
User Story 11: Testing

### ISSUE THREAD

**Issue by Asad-1I** [CharlesTack/JavaScriptQuiz#3]
User Story 11: Testing

**User Story 11: Testing:**
As a user I want to use a site which has been well tested and free from bugs, as well as having good colour contrast for ease of visibility so that I can have a great user experience.

**Acceptance Criteria:**
- [x] The site should be free from bugs
- [x] The site should use colours which are best for accessibility
- [x] Warnings should be minimised

**Tasks:**
- [x] Use Lighthouse in Google DevTools to achieve a rating of 80+
- [x] Use WebAIM to ensure main elements colour contrast is at least 4.5:1 (i.e. green and passing most tests)
- [x] Use W3C HTML/CSS checkers to ensure code is free of errors (some warning can be permitted for example those related to Bootstrap).
- [x] Use JavaScript debugger when needed.
