### ISSUE TITLE
User Story 14: Use of AI

### ISSUE THREAD

**Issue by Asad-1I** [CharlesTack/JavaScriptQuiz#4]
**User Story 14: Use of AI:**
As a user of the site I expect modern tools to be used in the creation and development of the site so that I get user best user experience.

**Acceptance Criteria:**
- [x] AI is used to assist with coding
- [x] AI is used to assist with validation and debugging
- [x] AI may be used to assist with image generation

**Tasks:**
- [x] Use Copilot in VS Code
- [x] Optional: Use AI image generators.
