### ISSUE TITLE
User Story 15: Documentation

### ISSUE THREAD

**Issue by Asad-1I** [CharlesTack/JavaScriptQuiz#5]
User Story 15: Documentation
**User Story 15: Documentation:**
As a fellow coder I would like to see the development documentation and marked up comments on the code so that I can get a better insight into the process and understanding of the code.

**Acceptance Criteria:**
- [x] A ReadMe document should be attached to the project and embedded in the repository
- [x] The ReadMe should be logically laid out for ease of reading
- [x] Comments should be used across all pages of the code (i.e. HTML, CSS and JS)

**Tasks:**
- [x] Create ReadMe
- [x] Use appropriate sections and headings as well as hyperlinks where possible to ease navigation
- [x] Ensure comments are added to the code frequently
