### ISSUE TITLE
User Story 2: Random Question Selection

### ISSUE THREAD

**Issue by Asad-1I** [CharlesTack/JavaScriptQuiz#6]
**User Story 2: Random Question Selection**
As a user, I want the quiz to present 10 randomly selected questions from the chosen difficulty level so that each quiz attempt feels unique.

**Acceptance Criteria:**
- [x] The application should have a bank of 10 questions.
- [x] The quiz should randomly select 10 of the questions.

**Tasks:**
- [x] Create a question bank with 10 questions.
- [x] Implement random selection logic to fetch 10 questions for each quiz attempt and change the order each attempt.
