### ISSUE TITLE
User Story 12: Planning

### ISSUE THREAD

**Issue by Asad-1I** [CharlesTack/JavaScriptQuiz#8]
**User Story 12: Planning:**
As a user, I need the site to be well thought out and designed with the site user in mind, with the processes used to indicate such so that I can have the best user experience.

**Acceptance Criteria:**
- [x] Use of wireframes to design appearance and layout
- [x] Appropriate imagery to be researched and utilised
- [x] An array of different technologies used to keep things fresh (i.e. Favicons, etc.)
- [x] Collaborative approach with full team to ensure consensus and diversity of ideas.

**Tasks:**
- [x] Use Balsamiq to create wireframes for mobile, tablet and laptop.
- [x] Use AI Generators or stock images to create/curate imagery for the site
- [x] Ensure formatting of images uses best practice guidelines (i.e. WebP or modern file types where available).
- [x] Use available tools, such as Google Meet/Slack to give everyone the ability to collaborate and put forward ideas equally.
