### ISSUE TITLE
User Story 8: Responsiveness

### ISSUE THREAD

**Issue by Asad-1I** [CharlesTack/JavaScriptQuiz#9]
**User Story 8: Responsiveness:**
As a user who has multiple devices I want the site to look as good as possible on a variety of different screen sizes, preferably on a single screen on each, so that I can have the best user experience.

**Acceptance Criteria:**
- [x] The site should look good on mobile, tablet and laptop/desktop.
- [x] The site should be on a single screen.

**Tasks:**
- [x] Use media queries to achieve the best responsive appearance on all device types.
- [x] Check appearance using different device types
- [x] Keep code concise to ensure appears on single screen and use comments.
